# This is a basic workflow to help you get started with GitHub Actions

name: CI/CD Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch: 


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_and_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Set up the .NET Core SDK
    - name: Tsering
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
        
    # Restore dependencies
    - name: is
      run: dotnet restore
      
    # Build the project 
    - name: Master
      run: dotnet build --no-restore
      
    # Run tests
    - name: Software
      run: dotnet test --no-build --verbosity normal
    
    # Building docker image locally
    - name: Engineer
      run: docker image build -t myimage:latest .
  
